# Generated by Django 4.1.2 on 2022-10-31 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Farmacia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('imagen', models.ImageField(upload_to='products')),
                ('ubicacion', models.CharField(max_length=255)),
                ('localidad', models.CharField(max_length=255)),
                ('turno_date', models.DateField()),
                ('turno_time', models.TimeField()),
            ],
        ),
    ]
